server:
  port: 8004
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        healthcheck:
            enabled: true
        lease:
            duration: 5

logging:
    file:
        ${APP_HOME}/logs/user_management.log

spring:
    application:
      name: usermanager
    data:   
        mongodb:
            host: localhost
            port: 27017
            database: eatrest
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000
  
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 60000
