server:
  port: 8761

eureka:
  instance:
    nonSecurePortEnabled:
      true
    securePortEnabled:
      false
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false